import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";

import { AuthContextProvider } from "@/context/AuthContext";

import RQProvider from "./_component/RQProvider";
import TokenLoginComponent from "./_component/TokenLoginComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Balance Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProvider>
          <AuthContextProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <TokenLoginComponent />
              <div className="root_container">{children}</div>
            </Suspense>
          </AuthContextProvider>
        </RQProvider>
        <div id="portal" />
      </body>
    </html>
  );
}
