import "./globals.css";

import type { Metadata } from "next";
import { Suspense } from "react";

import { AuthContextProvider } from "@/context/AuthContext";

import RQProvider from "./_component/RQProvider";
import TokenLoginComponent from "./_component/TokenLoginComponent";

export const metadata: Metadata = {
  title: "Balance Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQProvider>
          <AuthContextProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <TokenLoginComponent />
              {children}
            </Suspense>
          </AuthContextProvider>
        </RQProvider>
      </body>
    </html>
  );
}
