import "./globals.css";

import type { Metadata } from "next";
import { Suspense } from "react";

import RQProvider from "./_component/RQProvider";

export const metadata: Metadata = {
  title: "Balance Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQProvider>
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </RQProvider>
      </body>
    </html>
  );
}
